import time

#LOGJAM version
LOGJAM_VERSION = "0.1"

def AutogenString(src):
    v  = "/*\n"
    v += "* This file was auto-generated at {time} using LogJam version {v}.\n".format(time=time.ctime(), v=LOGJAM_VERSION)
    v += "* LogJam - https://github.com/SchrodingersGat/LogJam\n"
    v += "* Do not edit this file, any changes will be overwritten.\n"
    v += "* Edit the source file '{src}' from which this file was generated.\n".format(src=src)
    v += "*/\n\n"
    
    return v
    